### ISSUE TITLE
Can not create a super user account

### ISSUE THREAD

**Issue by ghost** [vanilophp/docs#13] opened 2020-04-22 22:16 UTC
Hi. Whenever I want to run this command it gives me an error and exits.

`php artisan appshell:super`

It does not let me to enter user info. It just says aborted and quits to the command prompt.

**Comment by fulopattila122** [comment] 2020-04-23 03:28
What is the error message you get? Perhaps a screenshot?

**Comment by fulopattila122** [comment] 2020-05-24 14:01
What PHP and Laravel version do you use?
Are you on Vanilo 1.2 version?

**Comment by fulopattila122** [comment] 2020-05-31 07:05
Duplicate of vanilophp/framework#78. Fixing it there.

**Closed as completed by fulopattila122** 2020-05-31 07:05 UTC
Labels: bug, duplicate

**Comment by fulopattila122** [comment] 2020-05-31 07:29
I cross-post the solution here as well, but all the details are in vanilophp/framework#78.

This issue affects PHP 7.4.0 on Windows. Upgrading PHP to 7.4.1 or higher should solve the problem.

> https://bugs.php.net/bug.php?id=78883
